services:
  emoncms:
    build: ./emoncms
    ports:
      - "8080:80"
    volumes:
      - emoncms_data:/var/lib/emoncms
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=emoncms
      - MYSQL_PASSWORD=secret
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=emoncms
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql

  nodered:
    build: ./nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data

  python:
    build: ./python
    volumes:
      - python_scripts:/scripts

  php:
    build: ./php
    volumes:
      - php_data:/var/www/html

volumes:
  emoncms_data:
  mysql_data:
  nodered_data:
  python_scripts:
  php_data:
